= A Poison Tree by William Blake

== A posion Tree
[verse]
----
I was angry with my friend:
I told my wrath, my wrath did end.
I was angry with my foe:
I told it not, my wrath did grow.

And I watered it in fears.
Night and morning with my tears:
And I sunned it with smiles.
And with soft deceitful wiles.

And it grew both day and night.
Till it bore an apple bright.
And my foe beheld it shine.
And he knew that it was mine.

And into my garden stole.
When the night had veild the pole;
In the morning glad I see;
My foe outstretchd beneath the tree.
----

== Interpretation

Blake originally gave ‘A Poison Tree’ the title ‘Christian Forbearance’. In summary, the speaker of the poem tells us that when he was angry with his friend he simply told his friend that he was annoyed, and that put an end to his bad feeling. But when he was angry with his enemy, he didn’t air his grievance to this foe, and so the anger grew.

In the second stanza, Blake turns to the central, title metaphor of his poem, likening his anger to a tree that he ‘watered’ with fear and resentment. Then, more curiously, he says that the false ‘smiles’ he put on whenever he saw his enemy acted like sunlight helping a tree to grow: by bottling up his anger he made it worse, and by putting on ‘soft deceitful wiles’ (i.e. tricks and cover-ups to hide his true feelings), his anger continued to grow and morphed into something more devious: the need for vengeance. Why? The implication of this ‘poison tree’ is that anger and hatred start to eat away at oneself: hatred always turns inward, corrupting into self-hatred. Because the speaker was forced to hide his anger, it made him act in a deceitful and false way, and thus his anger for his friend led him to despise himself for being driven to act deceitfully.

In the third stanza, an apple sprouts from this poison tree of anger. This ‘apple bright’ attracts the attention of his enemy, who then sneaked into the speaker’s garden one night and ate the apple from this tree; when the speaker finds his enemy the next morning, his foe is lying dead under the tree, having eaten the poisoned fruit.

This powerful and curious little poem is about the power of anger to become corrupted into something far more deadly and devious if it is not aired honestly. The enemy may have stolen the apple (and trespassed on the speaker’s property – he ‘stole’ into his garden, after all), but he was deceived into thinking that something deadly and poisonous (the speaker’s anger) was something nice and tasty (the apple). What are we to make of this rather involved metaphor? One possible interpretation is as follows: Blake is saying that repressing our righteous anger makes us scheme into finding underhand ways to get back at our enemies, and – consciously or unconsciously – we end up setting traps for our enemies in order to bring them down. The apple represents such wily and devious vengeance: it is significant that it is an apple that grows from Blake’s poison tree, and that the speaker’s enemy steals the apple, because this conjures up the Genesis story of Adam and Eve being deceitfully persuaded to eat the fruit from the forbidden Tree of Knowledge. Satan, disguised as a serpent, is the one responsible for cajoling Eve into eating the fruit, which is commonly depicted as an apple, like the apple in Blake’s poem. The Fall of Adam and Eve takes place, of course, in the paradise that is the Garden of Eden; Blake’s Edenic ‘garden’ is where his enemy meets his end. These parallels raise Blake’s parable of repressed anger and vengeance to Biblical heights.

‘A Poison Tree’ is one of English literature’s most striking explorations of the corrupting effects of anger. It is one of William Blake’s miniature masterpieces. What do you think of ‘A Poison Tree’, and what would you add to our analysis?
